# 01 — NumPy for Engineers

1. Introduction

- What is NumPy?

  - A Python library for numerical computing.

  - Optimized for array operations (faster than Python lists).

- Why Engineers Use It:

  - Efficient handling of large datasets.

  - Vectorized operations for simulations, process calculations, etc.

2. Importing NumPy

In [1]:
import numpy as np

3. Creating Arrays

1D Array

In [2]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


2D Array

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


Special Arrays

In [5]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity:\n", identity)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Array Attributes

In [6]:
print(arr2.shape)   # dimensions
print(arr2.size)    # number of elements
print(arr2.ndim)    # number of dimensions

(2, 3)
6
2


5. Indexing & Slicing

In [7]:
A = np.array([10, 20, 30, 40, 50])
print(A[0])      # first element
print(A[1:4])    # slicing

10
[20 30 40]


6. Mathematical Operations
Element-wise

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x * y)
print(np.sqrt(x))


[5 7 9]
[ 4 10 18]
[1.         1.41421356 1.73205081]


Chemical Engineering Example — Pressure Drop

$$
\Delta P = f \cdot \frac{L}{D} \cdot \frac{\rho v^2}{2}
$$



In [9]:
f = np.array([0.02, 0.025, 0.03])   # friction factors
L = 100                             # pipe length (m)
D = 0.5                             # diameter (m)
rho = 1000                          # density (kg/m³)
v = np.array([1.5, 2.0, 2.5])       # velocity (m/s)

delta_P = f * (L/D) * (rho * v**2 / 2)
print(delta_P)


[ 4500. 10000. 18750.]


7. Useful Functions

In [10]:
a = np.array([10, 20, 30, 40])
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))


25.0
40
10
100


9. Vectorization vs Loops (Performance Demo)

In [11]:
import time

# Using loop
start = time.time()
result_loop = [i**2 for i in range(1000000)]
end = time.time()
print("Loop time:", end - start)

# Using NumPy
start = time.time()
arr = np.arange(1000000)
result_numpy = arr**2
end = time.time()
print("NumPy time:", end - start)


Loop time: 0.08522343635559082
NumPy time: 0.006073951721191406


10. Mini Chemical Engineering Exercise

Heat Duty Calculation

$$
Q = \dot{m} \cdot C_p \cdot \Delta T
$$

In [12]:
m_dot = np.array([2.5, 3.0, 3.5])    # mass flow rate (kg/s)
Cp = 4.18                            # kJ/kg.K
delta_T = np.array([15, 20, 25])     # temperature rise (K)

Q = m_dot * Cp * delta_T  # kW
print(Q)


[156.75 250.8  365.75]
